export const FETCH_MOVIE_BEGIN   = 'FETCH_MOVIE_BEGIN';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAIL    = 'FETCH_MOVIE_FAIL';

export const FETCH_SEARCH_BEGIN   = 'FETCH_SEARCH_BEGIN';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAIL    = 'FETCH_SEARCH_FAIL';

export const FETCH_REVIEWS_BEGIN   = 'FETCH_REVIEWS_BEGIN';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAIL    = 'FETCH_REVIEWS_FAIL';

export const SAVE_REVIEWS_FAIL    = 'SAVE_REVIEWS_FAIL';
export const SAVE_REVIEWS_SUCCESS = 'SAVE_REVIEWS_SUCCESS';

export const DELETE_REVIEWS_FAIL    = 'DELETE_REVIEWS_FAIL';
export const DELETE_REVIEWS_SUCCESS = 'DELETE_REVIEWS_SUCCESS';

export const UPDATE_REVIEWS_FAIL    = 'UPDATE_REVIEWS_FAIL';
export const UPDATE_REVIEWS_SUCCESS = 'UPDATE_REVIEWS_SUCCESS';

export const FETCH_MOVIE_REVIEWS_BEGIN   = 'FETCH_MOVIE_REVIEWS_BEGIN';
export const FETCH_MOVIE_REVIEWS_SUCCESS = 'FETCH_MOVIE_REVIEWS_SUCCESS';
export const FETCH_MOVIE_REVIEWS_FAIL    = 'FETCH_MOVIE_REVIEWS_FAIL';
